# Generated by Django 6.0.4 on 2026-05-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='icono',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='modulo',
            name='ruta',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
