# Generated by Django 6.0.4 on 2026-05-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_modulo_icono_modulo_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
