# Generated by Django 6.0.6 on 2026-07-06 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '__first__'),
        ('tenants', '0003_modulo_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_plan', to='payments.plan'),
        ),
    ]
