# Generated by Django 6.0.6 on 2026-07-06 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_product_id', models.CharField(blank=True, max_length=100)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.PositiveIntegerField(help_text='Precio en centavos')),
                ('currency', models.CharField(default='mxn', max_length=3)),
                ('interval', models.CharField(blank=True, choices=[('day', 'Diario'), ('week', 'Semanal'), ('month', 'Mensual'), ('year', 'Anual')], help_text='Nulo = pago único, con valor = suscripción', max_length=10, null=True)),
                ('interval_count', models.PositiveSmallIntegerField(default=1, help_text='Cada cuántos intervalos se cobra (ej. 3 meses = interval=month, interval_count=3)')),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments_plans',
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=200, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200)),
                ('amount', models.PositiveIntegerField(help_text='Monto cobrado en centavos')),
                ('currency', models.CharField(default='mxn', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('succeeded', 'Exitoso'), ('failed', 'Fallido'), ('canceled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.plan')),
            ],
            options={
                'db_table': 'payments_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_refund_id', models.CharField(max_length=200, unique=True)),
                ('amount', models.PositiveIntegerField(help_text='Monto reembolsado en centavos')),
                ('currency', models.CharField(default='mxn', max_length=3)),
                ('reason', models.CharField(choices=[('duplicate', 'Duplicado'), ('fraudulent', 'Fraudulento'), ('requested_by_customer', 'Solicitado por cliente')], default='requested_by_customer', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('succeeded', 'Exitoso'), ('failed', 'Fallido'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
            ],
            options={
                'db_table': 'payments_refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=200, unique=True)),
                ('stripe_customer_id', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('past_due', 'Pago vencido'), ('unpaid', 'Sin pagar'), ('canceled', 'Cancelada'), ('incomplete', 'Incompleta'), ('trialing', 'En prueba'), ('paused', 'Pausada')], default='incomplete', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.plan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
