# Generated by Django 6.0.4 on 2026-05-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_seed_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='icono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='permiso',
            name='ruta',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='permiso',
            name='submodulo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
