# Generated by Django 6.0.4 on 2026-05-18 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_permiso_modulo_fk'),
        ('tenants', '0002_modulo_icono_modulo_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='icono',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='modulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to='tenants.modulo'),
        ),
    ]
